### ISSUE TITLE
Allow hiding the sidebar

### ISSUE THREAD

**Issue by briankendall** [getferdi/ferdi#1026]
I'd like a way to be able to hide the services sidebar. Sometimes I'm using a service where I want it to be truly full screen, for example when a video is being streamed. Currently I can remove all other elements on the screen _except_ the sidebar. It's possible to do this using the developer tools, but it'd be much better if there was a feature for it.

**Comment by TGlide** [comment]
Can I work on this?

**Comment by vantezzen** [comment]
Of course, go ahead!

**Comment by bittner** [comment]
Using a push-pin :pushpin: for that in the sidebar would be nice! (as in self-explanatory, maybe) :grimacing: 

`</feel-free-to-ignore>`

**Comment by TGlide** [comment]
I'm sorry, but I have unassigned myself from the issue! It proved to be too much to handle for me. But thank you for your time

**Comment by bittner** [comment]
This should be fairly easy, though. If you just inject CSS this can be done with something like this:

```css
.sidebar {
    width: 9px;
    transition: all 2s ease-in-out .5s;
    display: block;
}

.sidebar:hover {
    width: auto;
    transition: all 2s ease-in-out .5s;
    display: inline-flex;
}
```

Of course, that's just a hack. But it proves it's doable even with the simplest approach, even without doing React.

Try harder! :hammer_and_wrench: :construction_worker_woman:
