### ISSUE TITLE
Split View

### ISSUE THREAD

**Issue by barissenkal** [getferdi/ferdi#893]
**Is your feature request related to a problem? Please describe.**
I can only have one service on the screen when using ferdi.

**Describe the solution you'd like**
I would like to use two services side by side just like most code editors and iPad "split screen"

**Describe alternatives you've considered**
Having multiple ferdi windows would be another solution to this problem. One window per workspace would be even beter.

**Additional context**
A button could resize current service to left half of the window. Then user could drag-drop another service to right half placeholder.

**Comment by yann-soubeyrand** [comment]
Having the ability to detach a service in a separate window would be great ;-)

**Comment by arielaco** [comment]
Very interested in this

**Comment by DenysMb** [comment]
I'll really going to appreciate to use this functionality. Other alternatives like Stack or Biscuit have this option, but they don't have a Tray Icon, so it becomes unusable. If Ferdi had a Split View option, it will became the better app in their category.

**Comment by kladiv** [comment]
+1

**Comment by wsolorza** [comment]
bump

**Comment by Kazvko** [comment]
Since it already has a split screen option (for tasks), it could have a way to add any service there. It would be an alternative to implement something brand new.

**Comment by niutech** [comment]
As an inspiration, [Mosaic browser](https://github.com/mlajtos/mosaic#readme) (not the original one) is using Electron, React and Golden Layout to provide tiled view.

**Comment by niutech** [comment]
Actually, it was easier than I thought. Just add this CSS to `services.scss`: 
```css
.app .app__service {
    overflow-x: auto;
}
.services {
    display: flex;
    overflow: visible;
}
.services .services__webview {
    position: static;
    flex: 1 0 480px; /* min width of webview */
}
```
and here we go:

![Ferdi tile view](https://user-images.githubusercontent.com/384997/130630760-46da375e-1ed0-4084-8a41-4173ccd8c044.png)
